### PR TITLE
Add MinIO support

### PR DESCRIPTION
**Pull request by a2geek**
This adds support for MinIO - an S3 compatible product. The primary changes are around the IAM User as MinIO does not follow the AWS S3 endpoints. 

Changes:
* `awsiam` now has a `MinioUser` and a `NewUser()` func to create the proper `User`.
* `s3_bucket.go` did receive some tweaks coming back with the bucket name, ARN, and region. I left this as a general change.
* Added the concept of a "provider" - if it's not set to `minio`, it just defaults to `aws`. There is a corresponding `Provider` interface; this generally encapsulates the difference in endpoint determination (`s3.<region>.amazonaws.com` vs supplied endpoint).
* Allow self-signed certs (`insecure_skip_verify`).
* Added details to the returned credentials: endpoint, insecure_skip_verify.
* `main.go` sets these details up based on the configuration.

I did bump to Go 1.14, simply because that was on my desktop (I don't think I have anything specific that required it).

The bulk of the files are due to pulling in the MinIO client library and doing `go mod tidy` a couple of times. :disappointed: 

Looking for commentary and suggestions around making this a part of the S3 Broker.

Thanks!

### CODE REVIEW

**Comment by bengerman13** [comment]
hey @a2geek thanks for the PR!

it looks like something's wrong with the minio package vendoring, causing the tests to fail. Can you get that sorted and then I can get this merged for you?

**Comment by a2geek** [comment]
Yeah, I'll take a look. I did try tinkering a bit earlier (you'll see a few commits around that).  When I run `ginkgo` on my desktop, I get this:
```
$ ~/go/bin/ginkgo -r
[1600011943] Main Suite - 5/5 specs ••••• SUCCESS! 91.662µs PASS
[1600011943] AWS IAM Suite - 33/33 specs ••••••••••••••••••••••••••••••••• SUCCESS! 1.496945ms PASS
PASS
testing: warning: no tests to run
Found no test suites, did you forget to run "ginkgo bootstrap"?
Ginkgo ran 3 suites in 1.467514666s
Test Suite Passed
```
Looks like it is the same version of Ginkgo:
```
$ ~/go/bin/ginkgo version
Ginkgo Version 1.14.1
```
So I was rather confused. But I didn't try a clean copy. So maybe I've got cruft somewhere, somehow ... :man_shrugging:

**Comment by a2geek** [comment]
I think I found it... `.gitignore` is excluding `pkg` ([code](https://github.com/a2geek/s3-broker/blob/add-minio-support/.gitignore#L3)). If I change that line to be `/pkg` (presuming this is a project 'root' level exclusion), then there are additional packages that need to be committed:
```
$ git status
On branch add-minio-support
Your branch is up to date with 'origin/add-minio-support'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/github.com/minio/minio-go/v7/pkg/
	vendor/github.com/minio/minio/pkg/
	vendor/github.com/pkg/errors/Makefile
	vendor/github.com/pkg/errors/go113.go

no changes added to commit (use "git add" and/or "git commit -a")
```

I see the MinIO packages, which we definitely want. I see a couple of additional files from `pkg/errors` ([repo](https://github.com/pkg/errors)) as well. I am going to assume that don't intend to exclude them and push the update via the branch.

**Review by bengerman13 — APPROVED** [review]
LGTM. Thanks @a2geek !

**Pull request merged**
